name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGISTRY: "haraldka"
  IMAGE_NAME: "shorter"
  CONTAINER_NAME: "shorter"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.17.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...